// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addresses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const clearDefaultForUser = `-- name: ClearDefaultForUser :exec
UPDATE addresses SET is_default = false, updated_at = now()
WHERE user_id = $1 AND is_default = true
`

func (q *Queries) ClearDefaultForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultForUser, userID)
	return err
}

const countAddressesByUserID = `-- name: CountAddressesByUserID :one
SELECT count(*) FROM addresses WHERE user_id = $1
`

func (q *Queries) CountAddressesByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAddressesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (user_id, label, line1, line2, city, region, phone, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, label, line1, line2, city, region, phone, is_default, created_at, updated_at
`

type CreateAddressParams struct {
	UserID    uuid.UUID
	Label     string
	Line1     string
	Line2     string
	City      string
	Region    string
	Phone     string
	IsDefault bool
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.Label,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.Region,
		arg.Phone,
		arg.IsDefault,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.Region,
		&i.Phone,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses WHERE id = $1
`

func (q *Queries) DeleteAddress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAddress, id)
	return err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, user_id, label, line1, line2, city, region, phone, is_default, created_at, updated_at
FROM addresses
WHERE id = $1
`

func (q *Queries) GetAddressByID(ctx context.Context, id uuid.UUID) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressByID, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.Region,
		&i.Phone,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOldestOtherAddress = `-- name: GetOldestOtherAddress :one
SELECT id
FROM addresses
WHERE user_id = $1 AND id != $2
ORDER BY created_at ASC
LIMIT 1
`

type GetOldestOtherAddressParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetOldestOtherAddress(ctx context.Context, arg GetOldestOtherAddressParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getOldestOtherAddress, arg.UserID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAddressesByUserID = `-- name: ListAddressesByUserID :many
SELECT id, user_id, label, line1, line2, city, region, phone, is_default, created_at, updated_at
FROM addresses
WHERE user_id = $1
ORDER BY is_default DESC, created_at DESC
`

func (q *Queries) ListAddressesByUserID(ctx context.Context, userID uuid.UUID) ([]Address, error) {
	rows, err := q.db.Query(ctx, listAddressesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Address
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.Region,
			&i.Phone,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultAddress = `-- name: SetDefaultAddress :one
UPDATE addresses SET is_default = true, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, label, line1, line2, city, region, phone, is_default, created_at, updated_at
`

type SetDefaultAddressParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, setDefaultAddress, arg.ID, arg.UserID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.Region,
		&i.Phone,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAddress = `-- name: UpdateAddress :one
UPDATE addresses
SET label = $2, line1 = $3, line2 = $4, city = $5, region = $6, phone = $7, updated_at = now()
WHERE id = $1
RETURNING id, user_id, label, line1, line2, city, region, phone, is_default, created_at, updated_at
`

type UpdateAddressParams struct {
	ID     uuid.UUID
	Label  string
	Line1  string
	Line2  string
	City   string
	Region string
	Phone  string
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, updateAddress,
		arg.ID,
		arg.Label,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.Region,
		arg.Phone,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.Region,
		&i.Phone,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
