// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAllCustomers = `-- name: CountAllCustomers :one
SELECT COUNT(DISTINCT user_id)
FROM user_roles
WHERE role = 'customer'
`

// Counts total customers
func (q *Queries) CountAllCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllOrders = `-- name: CountAllOrders :one
SELECT COUNT(*)
FROM orders
WHERE ($1::text = '' OR status = $1)
  AND ($2::timestamptz IS NULL OR created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR created_at <= $3::timestamptz)
`

type CountAllOrdersParams struct {
	Status   *string
	DateFrom pgtype.Timestamptz
	DateTo   pgtype.Timestamptz
}

// Counts orders with optional status and date filters
func (q *Queries) CountAllOrders(ctx context.Context, arg CountAllOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllOrders, arg.Status, arg.DateFrom, arg.DateTo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCustomerStats = `-- name: GetCustomerStats :one
SELECT
  (SELECT COUNT(DISTINCT user_id) FROM user_roles WHERE role = 'customer')::int AS total_customers,
  (SELECT COUNT(DISTINCT user_id) FROM user_roles ur
   JOIN users u ON u.id = ur.user_id
   WHERE ur.role = 'customer'
   AND EXISTS (SELECT 1 FROM orders o WHERE o.user_id = u.id AND o.created_at >= NOW() - INTERVAL '30 days')
  )::int AS active_customers_30d,
  -- Customers who have placed at least one order
  (SELECT COUNT(DISTINCT o.user_id) FROM orders o
   JOIN user_roles ur ON ur.user_id = o.user_id
   WHERE ur.role = 'customer'
  )::int AS customers_with_orders
`

type GetCustomerStatsRow struct {
	TotalCustomers      int32
	ActiveCustomers30d  int32
	CustomersWithOrders int32
}

// Returns customer statistics
func (q *Queries) GetCustomerStats(ctx context.Context) (GetCustomerStatsRow, error) {
	row := q.db.QueryRow(ctx, getCustomerStats)
	var i GetCustomerStatsRow
	err := row.Scan(&i.TotalCustomers, &i.ActiveCustomers30d, &i.CustomersWithOrders)
	return i, err
}

const getDashboardStats = `-- name: GetDashboardStats :one

SELECT
  -- Total revenue from paid orders
  (SELECT COALESCE(SUM(total_ghs_minor), 0) FROM orders WHERE status != 'pending' AND status != 'cancelled')::bigint AS total_revenue_ghs_minor,
  -- Total order count
  (SELECT COUNT(*) FROM orders)::int AS total_orders,
  -- Pending order count
  (SELECT COUNT(*) FROM orders WHERE status = 'pending')::int AS pending_orders,
  -- Paid order count
  (SELECT COUNT(*) FROM orders WHERE status = 'paid')::int AS paid_orders,
  -- Shipped order count
  (SELECT COUNT(*) FROM orders WHERE status = 'shipped')::int AS shipped_orders,
  -- Delivered order count
  (SELECT COUNT(*) FROM orders WHERE status = 'delivered')::int AS delivered_orders,
  -- Total customers (users with customer role)
  (SELECT COUNT(DISTINCT user_id) FROM user_roles WHERE role = 'customer')::int AS total_customers,
  -- Total products
  (SELECT COUNT(*) FROM products)::int AS total_products
`

type GetDashboardStatsRow struct {
	TotalRevenueGhsMinor int64
	TotalOrders          int32
	PendingOrders        int32
	PaidOrders           int32
	ShippedOrders        int32
	DeliveredOrders      int32
	TotalCustomers       int32
	TotalProducts        int32
}

// Admin queries for Rue Cosmetics dashboard and analytics
// These queries provide aggregate data for admin views
// Returns summary statistics for the admin dashboard
func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalRevenueGhsMinor,
		&i.TotalOrders,
		&i.PendingOrders,
		&i.PaidOrders,
		&i.ShippedOrders,
		&i.DeliveredOrders,
		&i.TotalCustomers,
		&i.TotalProducts,
	)
	return i, err
}

const getOrderAnalytics = `-- name: GetOrderAnalytics :one
SELECT
  (SELECT COUNT(*) FROM orders WHERE status = 'pending')::int AS pending_count,
  (SELECT COUNT(*) FROM orders WHERE status = 'paid')::int AS paid_count,
  (SELECT COUNT(*) FROM orders WHERE status = 'fulfilled')::int AS fulfilled_count,
  (SELECT COUNT(*) FROM orders WHERE status = 'shipped')::int AS shipped_count,
  (SELECT COUNT(*) FROM orders WHERE status = 'delivered')::int AS delivered_count,
  (SELECT COUNT(*) FROM orders WHERE status = 'cancelled')::int AS cancelled_count,
  (SELECT COUNT(*) FROM orders WHERE status = 'refunded')::int AS refunded_count,
  (SELECT COALESCE(SUM(total_ghs_minor), 0) FROM orders WHERE status = 'paid')::bigint AS paid_revenue_ghs_minor,
  (SELECT COALESCE(SUM(total_ghs_minor), 0) FROM orders WHERE status = 'delivered')::bigint AS delivered_revenue_ghs_minor,
  (SELECT COALESCE(SUM(total_ghs_minor), 0) FROM orders WHERE status IN ('paid', 'delivered'))::bigint AS total_completed_revenue_ghs_minor
`

type GetOrderAnalyticsRow struct {
	PendingCount                  int32
	PaidCount                     int32
	FulfilledCount                int32
	ShippedCount                  int32
	DeliveredCount                int32
	CancelledCount                int32
	RefundedCount                 int32
	PaidRevenueGhsMinor           int64
	DeliveredRevenueGhsMinor      int64
	TotalCompletedRevenueGhsMinor int64
}

// Returns order counts and revenue grouped by status
func (q *Queries) GetOrderAnalytics(ctx context.Context) (GetOrderAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, getOrderAnalytics)
	var i GetOrderAnalyticsRow
	err := row.Scan(
		&i.PendingCount,
		&i.PaidCount,
		&i.FulfilledCount,
		&i.ShippedCount,
		&i.DeliveredCount,
		&i.CancelledCount,
		&i.RefundedCount,
		&i.PaidRevenueGhsMinor,
		&i.DeliveredRevenueGhsMinor,
		&i.TotalCompletedRevenueGhsMinor,
	)
	return i, err
}

const getProductStats = `-- name: GetProductStats :one
SELECT
  (SELECT COUNT(*) FROM products)::int AS total_products,
  -- Products with no stock (assuming stock would be tracked; for now using placeholder)
  (SELECT COUNT(*) FROM products WHERE tags && ARRAY['out-of-stock'])::int AS out_of_stock_count,
  -- Products tagged as low stock
  (SELECT COUNT(*) FROM products WHERE tags && ARRAY['low-stock'])::int AS low_stock_count,
  -- Count by tone
  (SELECT COUNT(*) FROM products WHERE tone = 'lavender')::int AS lavender_count,
  (SELECT COUNT(*) FROM products WHERE tone = 'rose')::int AS rose_count,
  (SELECT COUNT(*) FROM products WHERE tone = 'cream')::int AS cream_count,
  (SELECT COUNT(*) FROM products WHERE tone = 'ink')::int AS ink_count
`

type GetProductStatsRow struct {
	TotalProducts   int32
	OutOfStockCount int32
	LowStockCount   int32
	LavenderCount   int32
	RoseCount       int32
	CreamCount      int32
	InkCount        int32
}

// Returns product statistics
func (q *Queries) GetProductStats(ctx context.Context) (GetProductStatsRow, error) {
	row := q.db.QueryRow(ctx, getProductStats)
	var i GetProductStatsRow
	err := row.Scan(
		&i.TotalProducts,
		&i.OutOfStockCount,
		&i.LowStockCount,
		&i.LavenderCount,
		&i.RoseCount,
		&i.CreamCount,
		&i.InkCount,
	)
	return i, err
}

const getRecentOrders = `-- name: GetRecentOrders :many
SELECT
  o.id,
  o.user_id,
  o.status,
  o.total_ghs_minor,
  o.paystack_reference,
  o.created_at,
  u.email AS customer_email,
  u.name AS customer_name
FROM orders o
JOIN users u ON u.id = o.user_id
ORDER BY o.created_at DESC
LIMIT $1
`

type GetRecentOrdersRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Status            string
	TotalGhsMinor     int64
	PaystackReference string
	CreatedAt         pgtype.Timestamptz
	CustomerEmail     string
	CustomerName      string
}

// Returns the most recent orders with customer information
func (q *Queries) GetRecentOrders(ctx context.Context, limit int32) ([]GetRecentOrdersRow, error) {
	rows, err := q.db.Query(ctx, getRecentOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentOrdersRow
	for rows.Next() {
		var i GetRecentOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalGhsMinor,
			&i.PaystackReference,
			&i.CreatedAt,
			&i.CustomerEmail,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueByCategory = `-- name: GetRevenueByCategory :many
SELECT
  cat.id,
  cat.slug,
  cat.label AS category_name,
  COUNT(DISTINCT o.id)::int AS order_count,
  COALESCE(SUM(oi.qty * oi.unit_price_ghs_minor), 0)::bigint AS revenue_ghs_minor
FROM categories cat
LEFT JOIN products p ON p.category_id = cat.id
LEFT JOIN order_items oi ON oi.product_id = p.id
LEFT JOIN orders o ON o.id = oi.order_id AND o.status IN ('paid', 'delivered')
GROUP BY cat.id, cat.slug, cat.label
ORDER BY revenue_ghs_minor DESC
`

type GetRevenueByCategoryRow struct {
	ID              uuid.UUID
	Slug            string
	CategoryName    string
	OrderCount      int32
	RevenueGhsMinor int64
}

// Returns revenue breakdown by product category
func (q *Queries) GetRevenueByCategory(ctx context.Context) ([]GetRevenueByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getRevenueByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueByCategoryRow
	for rows.Next() {
		var i GetRevenueByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.CategoryName,
			&i.OrderCount,
			&i.RevenueGhsMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueByDate = `-- name: GetRevenueByDate :many
SELECT
  date_trunc($1, o.created_at)::date AS revenue_date,
  COUNT(*)::int AS order_count,
  COALESCE(SUM(o.total_ghs_minor), 0)::bigint AS revenue_ghs_minor
FROM orders o
WHERE o.status IN ('paid', 'delivered')
  AND o.created_at >= $2::timestamptz
  AND o.created_at <= $3::timestamptz
GROUP BY date_trunc($1, o.created_at)
ORDER BY revenue_date DESC
`

type GetRevenueByDateParams struct {
	Granularity *string
	DateFrom    pgtype.Timestamptz
	DateTo      pgtype.Timestamptz
}

type GetRevenueByDateRow struct {
	RevenueDate     pgtype.Date
	OrderCount      int32
	RevenueGhsMinor int64
}

// Returns revenue aggregated by date (daily, weekly, or monthly)
func (q *Queries) GetRevenueByDate(ctx context.Context, arg GetRevenueByDateParams) ([]GetRevenueByDateRow, error) {
	rows, err := q.db.Query(ctx, getRevenueByDate, arg.Granularity, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueByDateRow
	for rows.Next() {
		var i GetRevenueByDateRow
		if err := rows.Scan(&i.RevenueDate, &i.OrderCount, &i.RevenueGhsMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopProducts = `-- name: GetTopProducts :many
SELECT
  p.id,
  p.slug,
  p.name,
  p.brand_id,
  p.category_id,
  p.price_ghs_minor,
  p.tone,
  p.image_path,
  c.name AS brand_name,
  cat.label AS category_label,
  COALESCE(SUM(oi.qty), 0)::int AS total_sold,
  COALESCE(SUM(oi.qty * oi.unit_price_ghs_minor), 0)::bigint AS total_revenue_ghs_minor
FROM products p
LEFT JOIN order_items oi ON oi.product_id = p.id
LEFT JOIN orders o ON o.id = oi.order_id AND o.status IN ('paid', 'delivered')
LEFT JOIN brands c ON c.id = p.brand_id
LEFT JOIN categories cat ON cat.id = p.category_id
GROUP BY p.id, p.slug, p.name, p.brand_id, p.category_id, p.price_ghs_minor, p.tone, p.image_path, c.name, cat.label
HAVING COALESCE(SUM(oi.qty), 0) > 0
ORDER BY total_revenue_ghs_minor DESC
LIMIT $1
`

type GetTopProductsRow struct {
	ID                   uuid.UUID
	Slug                 string
	Name                 string
	BrandID              uuid.UUID
	CategoryID           uuid.UUID
	PriceGhsMinor        int64
	Tone                 string
	ImagePath            string
	BrandName            *string
	CategoryLabel        *string
	TotalSold            int32
	TotalRevenueGhsMinor int64
}

// Returns top-selling products by revenue
func (q *Queries) GetTopProducts(ctx context.Context, limit int32) ([]GetTopProductsRow, error) {
	rows, err := q.db.Query(ctx, getTopProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopProductsRow
	for rows.Next() {
		var i GetTopProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BrandID,
			&i.CategoryID,
			&i.PriceGhsMinor,
			&i.Tone,
			&i.ImagePath,
			&i.BrandName,
			&i.CategoryLabel,
			&i.TotalSold,
			&i.TotalRevenueGhsMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrderHistory = `-- name: InsertOrderHistory :one
INSERT INTO order_history (order_id, old_status, new_status, changed_by_user_id, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, old_status, new_status, changed_by_user_id, changed_at, note
`

type InsertOrderHistoryParams struct {
	OrderID         uuid.UUID
	OldStatus       string
	NewStatus       string
	ChangedByUserID pgtype.UUID
	Note            *string
}

// Creates an audit record for an order status change
func (q *Queries) InsertOrderHistory(ctx context.Context, arg InsertOrderHistoryParams) (OrderHistory, error) {
	row := q.db.QueryRow(ctx, insertOrderHistory,
		arg.OrderID,
		arg.OldStatus,
		arg.NewStatus,
		arg.ChangedByUserID,
		arg.Note,
	)
	var i OrderHistory
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.OldStatus,
		&i.NewStatus,
		&i.ChangedByUserID,
		&i.ChangedAt,
		&i.Note,
	)
	return i, err
}

const listAllCustomers = `-- name: ListAllCustomers :many
SELECT DISTINCT
  u.id,
  u.email,
  u.name,
  u.email_verified,
  u.created_at,
  (SELECT COUNT(*) FROM orders WHERE user_id = u.id)::int AS order_count,
  (SELECT COALESCE(SUM(total_ghs_minor), 0) FROM orders WHERE user_id = u.id AND status IN ('paid', 'delivered'))::bigint AS lifetime_value_ghs_minor,
  -- Last order date
  (SELECT MAX(created_at) FROM orders WHERE user_id = u.id) AS last_order_at
FROM users u
WHERE EXISTS (SELECT 1 FROM user_roles ur WHERE ur.user_id = u.id AND ur.role = 'customer')
ORDER BY u.created_at DESC
LIMIT $2 OFFSET $1
`

type ListAllCustomersParams struct {
	Offset *int32
	Limit  *int32
}

type ListAllCustomersRow struct {
	ID                    uuid.UUID
	Email                 string
	Name                  string
	EmailVerified         bool
	CreatedAt             pgtype.Timestamptz
	OrderCount            int32
	LifetimeValueGhsMinor int64
	LastOrderAt           interface{}
}

// Returns paginated list of all customers with order counts and lifetime value
func (q *Queries) ListAllCustomers(ctx context.Context, arg ListAllCustomersParams) ([]ListAllCustomersRow, error) {
	rows, err := q.db.Query(ctx, listAllCustomers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCustomersRow
	for rows.Next() {
		var i ListAllCustomersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.EmailVerified,
			&i.CreatedAt,
			&i.OrderCount,
			&i.LifetimeValueGhsMinor,
			&i.LastOrderAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllOrders = `-- name: ListAllOrders :many
SELECT
  o.id,
  o.user_id,
  o.status,
  o.subtotal_ghs_minor,
  o.shipping_ghs_minor,
  o.total_ghs_minor,
  o.paystack_reference,
  o.created_at,
  o.updated_at,
  u.email AS customer_email,
  u.name AS customer_name,
  -- Extract phone from shipping_address JSONB
  (o.shipping_address->>'phone') AS customer_phone
FROM orders o
JOIN users u ON u.id = o.user_id
WHERE ($1::text = '' OR o.status = $1)
  AND ($2::timestamptz IS NULL OR o.created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR o.created_at <= $3::timestamptz)
ORDER BY o.created_at DESC
LIMIT $5 OFFSET $4
`

type ListAllOrdersParams struct {
	Status   *string
	DateFrom pgtype.Timestamptz
	DateTo   pgtype.Timestamptz
	Offset   *int32
	Limit    *int32
}

type ListAllOrdersRow struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Status            string
	SubtotalGhsMinor  int64
	ShippingGhsMinor  int64
	TotalGhsMinor     int64
	PaystackReference string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	CustomerEmail     string
	CustomerName      string
	CustomerPhone     interface{}
}

// Returns paginated list of all orders with optional status filter
func (q *Queries) ListAllOrders(ctx context.Context, arg ListAllOrdersParams) ([]ListAllOrdersRow, error) {
	rows, err := q.db.Query(ctx, listAllOrders,
		arg.Status,
		arg.DateFrom,
		arg.DateTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllOrdersRow
	for rows.Next() {
		var i ListAllOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.SubtotalGhsMinor,
			&i.ShippingGhsMinor,
			&i.TotalGhsMinor,
			&i.PaystackReference,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.CustomerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, subtotal_ghs_minor, shipping_ghs_minor,
          total_ghs_minor, paystack_reference, paystack_transaction_id,
          shipping_address, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID
	Status string
}

// Updates the status of an order
func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalGhsMinor,
		&i.ShippingGhsMinor,
		&i.TotalGhsMinor,
		&i.PaystackReference,
		&i.PaystackTransactionID,
		&i.ShippingAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
