// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_roles (user_id, role) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddUserRoleParams struct {
	UserID uuid.UUID
	Role   string
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.Exec(ctx, addUserRole, arg.UserID, arg.Role)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, expires_at, ip, user_agent, created_at, last_used_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	Ip        *netip.Addr
	UserAgent string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, email_verified)
VALUES ($1, $2, $3)
RETURNING id, email, name, image, email_verified, created_at, updated_at
`

type CreateUserParams struct {
	Email         string
	Name          string
	EmailVerified bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.EmailVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVerificationToken = `-- name: CreateVerificationToken :one
INSERT INTO verification_tokens (user_id, kind, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, kind, token_hash, expires_at, used_at, created_at
`

type CreateVerificationTokenParams struct {
	UserID    uuid.UUID
	Kind      string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, createVerificationToken,
		arg.UserID,
		arg.Kind,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOtherSessionsForUser = `-- name: DeleteOtherSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1 AND id <> $2
`

type DeleteOtherSessionsForUserParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteOtherSessionsForUser(ctx context.Context, arg DeleteOtherSessionsForUserParams) error {
	_, err := q.db.Exec(ctx, deleteOtherSessionsForUser, arg.UserID, arg.ID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, provider, provider_account_id, created_at
FROM oauth_accounts WHERE provider = $1 AND provider_account_id = $2
`

type GetOAuthAccountParams struct {
	Provider          string
	ProviderAccountID string
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.Provider, arg.ProviderAccountID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordCredentialByUserID = `-- name: GetPasswordCredentialByUserID :one
SELECT user_id, password_hash, updated_at
FROM password_credentials WHERE user_id = $1
`

func (q *Queries) GetPasswordCredentialByUserID(ctx context.Context, userID uuid.UUID) (PasswordCredential, error) {
	row := q.db.QueryRow(ctx, getPasswordCredentialByUserID, userID)
	var i PasswordCredential
	err := row.Scan(&i.UserID, &i.PasswordHash, &i.UpdatedAt)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.user_id, s.token_hash, s.expires_at, s.ip, s.user_agent, s.created_at, s.last_used_at
FROM sessions s
WHERE s.token_hash = $1 AND s.expires_at > now()
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getUnusedVerificationToken = `-- name: GetUnusedVerificationToken :one
SELECT id, user_id, kind, token_hash, expires_at, used_at, created_at
FROM verification_tokens
WHERE token_hash = $1 AND kind = $2 AND used_at IS NULL AND expires_at > now()
`

type GetUnusedVerificationTokenParams struct {
	TokenHash []byte
	Kind      string
}

func (q *Queries) GetUnusedVerificationToken(ctx context.Context, arg GetUnusedVerificationTokenParams) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, getUnusedVerificationToken, arg.TokenHash, arg.Kind)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, image, email_verified, created_at, updated_at
FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, image, email_verified, created_at, updated_at
FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRolesForUser = `-- name: ListRolesForUser :many
SELECT role FROM user_roles WHERE user_id = $1 ORDER BY role
`

func (q *Queries) ListRolesForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVerificationTokenUsed = `-- name: MarkVerificationTokenUsed :exec
UPDATE verification_tokens SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkVerificationTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markVerificationTokenUsed, id)
	return err
}

const refreshSessionLastUsed = `-- name: RefreshSessionLastUsed :exec
UPDATE sessions SET last_used_at = now() WHERE id = $1
`

func (q *Queries) RefreshSessionLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, refreshSessionLastUsed, id)
	return err
}

const rollSessionExpiry = `-- name: RollSessionExpiry :exec
UPDATE sessions SET expires_at = $2, last_used_at = now() WHERE id = $1
`

type RollSessionExpiryParams struct {
	ID        uuid.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) RollSessionExpiry(ctx context.Context, arg RollSessionExpiryParams) error {
	_, err := q.db.Exec(ctx, rollSessionExpiry, arg.ID, arg.ExpiresAt)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = COALESCE($1, name),
    updated_at = now()
WHERE id = $2
RETURNING id, email, name, image, email_verified, created_at, updated_at
`

type UpdateUserParams struct {
	Name *string
	ID   uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Name, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Image,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :exec
UPDATE users SET email_verified = $2, updated_at = now() WHERE id = $1
`

type UpdateUserEmailVerifiedParams struct {
	ID            uuid.UUID
	EmailVerified bool
}

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, arg UpdateUserEmailVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerified, arg.ID, arg.EmailVerified)
	return err
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users SET name = $2, updated_at = now() WHERE id = $1
`

type UpdateUserNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.ID, arg.Name)
	return err
}

const upsertOAuthAccount = `-- name: UpsertOAuthAccount :exec
INSERT INTO oauth_accounts (user_id, provider, provider_account_id)
VALUES ($1, $2, $3)
ON CONFLICT (provider, provider_account_id) DO NOTHING
`

type UpsertOAuthAccountParams struct {
	UserID            uuid.UUID
	Provider          string
	ProviderAccountID string
}

func (q *Queries) UpsertOAuthAccount(ctx context.Context, arg UpsertOAuthAccountParams) error {
	_, err := q.db.Exec(ctx, upsertOAuthAccount, arg.UserID, arg.Provider, arg.ProviderAccountID)
	return err
}

const upsertPasswordCredential = `-- name: UpsertPasswordCredential :exec
INSERT INTO password_credentials (user_id, password_hash, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (user_id) DO UPDATE
SET password_hash = EXCLUDED.password_hash, updated_at = now()
`

type UpsertPasswordCredentialParams struct {
	UserID       uuid.UUID
	PasswordHash string
}

func (q *Queries) UpsertPasswordCredential(ctx context.Context, arg UpsertPasswordCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertPasswordCredential, arg.UserID, arg.PasswordHash)
	return err
}
