// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCartForGuest = `-- name: CreateCartForGuest :one
INSERT INTO carts (guest_token) VALUES ($1) RETURNING id, user_id, guest_token, created_at, updated_at
`

func (q *Queries) CreateCartForGuest(ctx context.Context, guestToken *string) (Cart, error) {
	row := q.db.QueryRow(ctx, createCartForGuest, guestToken)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCartForUser = `-- name: CreateCartForUser :one
INSERT INTO carts (user_id) VALUES ($1) RETURNING id, user_id, guest_token, created_at, updated_at
`

func (q *Queries) CreateCartForUser(ctx context.Context, userID pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, createCartForUser, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM carts WHERE id = $1
`

func (q *Queries) DeleteCart(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCart, id)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items WHERE id = $1 AND cart_id = $2
`

type DeleteCartItemParams struct {
	ID     uuid.UUID
	CartID uuid.UUID
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.Exec(ctx, deleteCartItem, arg.ID, arg.CartID)
	return err
}

const getCartByGuestToken = `-- name: GetCartByGuestToken :one
SELECT id, user_id, guest_token, created_at, updated_at FROM carts WHERE guest_token = $1
`

func (q *Queries) GetCartByGuestToken(ctx context.Context, guestToken *string) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByGuestToken, guestToken)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartByUserID = `-- name: GetCartByUserID :one
SELECT id, user_id, guest_token, created_at, updated_at FROM carts WHERE user_id = $1
`

func (q *Queries) GetCartByUserID(ctx context.Context, userID pgtype.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByUserID, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GuestToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemByID = `-- name: GetCartItemByID :one
SELECT id, cart_id, product_id, qty, unit_price_ghs_minor, created_at, updated_at
FROM cart_items
WHERE id = $1 AND cart_id = $2
`

type GetCartItemByIDParams struct {
	ID     uuid.UUID
	CartID uuid.UUID
}

func (q *Queries) GetCartItemByID(ctx context.Context, arg GetCartItemByIDParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItemByID, arg.ID, arg.CartID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Qty,
		&i.UnitPriceGhsMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemByProduct = `-- name: GetCartItemByProduct :one
SELECT id, cart_id, product_id, qty, unit_price_ghs_minor, created_at, updated_at
FROM cart_items
WHERE cart_id = $1 AND product_id = $2
`

type GetCartItemByProductParams struct {
	CartID    uuid.UUID
	ProductID uuid.UUID
}

func (q *Queries) GetCartItemByProduct(ctx context.Context, arg GetCartItemByProductParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItemByProduct, arg.CartID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Qty,
		&i.UnitPriceGhsMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT id, cart_id, product_id, qty, unit_price_ghs_minor, created_at, updated_at
FROM cart_items
WHERE cart_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCartItems(ctx context.Context, cartID uuid.UUID) ([]CartItem, error) {
	rows, err := q.db.Query(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ProductID,
			&i.Qty,
			&i.UnitPriceGhsMinor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCartItemQty = `-- name: SetCartItemQty :exec
UPDATE cart_items SET qty = $3, updated_at = now()
WHERE id = $1 AND cart_id = $2
`

type SetCartItemQtyParams struct {
	ID     uuid.UUID
	CartID uuid.UUID
	Qty    int32
}

func (q *Queries) SetCartItemQty(ctx context.Context, arg SetCartItemQtyParams) error {
	_, err := q.db.Exec(ctx, setCartItemQty, arg.ID, arg.CartID, arg.Qty)
	return err
}

const touchCart = `-- name: TouchCart :exec
UPDATE carts SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchCart(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchCart, id)
	return err
}

const upsertCartItemAddQty = `-- name: UpsertCartItemAddQty :one
INSERT INTO cart_items (cart_id, product_id, qty, unit_price_ghs_minor)
VALUES ($1, $2, $3, $4)
ON CONFLICT (cart_id, product_id) DO UPDATE
SET qty = cart_items.qty + EXCLUDED.qty, updated_at = now()
RETURNING id, cart_id, product_id, qty, unit_price_ghs_minor, created_at, updated_at
`

type UpsertCartItemAddQtyParams struct {
	CartID            uuid.UUID
	ProductID         uuid.UUID
	Qty               int32
	UnitPriceGhsMinor int64
}

func (q *Queries) UpsertCartItemAddQty(ctx context.Context, arg UpsertCartItemAddQtyParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItemAddQty,
		arg.CartID,
		arg.ProductID,
		arg.Qty,
		arg.UnitPriceGhsMinor,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.Qty,
		&i.UnitPriceGhsMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
