// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*)
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
LEFT JOIN brands     b ON b.id = p.brand_id
WHERE ($1::text IS NULL OR c.slug = $1)
  AND ($2::text    IS NULL OR b.slug = $2)
  AND ($3::text           IS NULL OR p.tags && ARRAY[$3::text])
  AND ($4::text             IS NULL OR p.name ILIKE '%' || $4 || '%')
`

type CountProductsParams struct {
	CategorySlug *string
	BrandSlug    *string
	Tag          *string
	Q            *string
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts,
		arg.CategorySlug,
		arg.BrandSlug,
		arg.Tag,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBrandByID = `-- name: GetBrandByID :one
SELECT id, slug, name FROM brands WHERE id = $1
`

func (q *Queries) GetBrandByID(ctx context.Context, id uuid.UUID) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByID, id)
	var i Brand
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, slug, name, brand_id, category_id, price_ghs_minor, was_price_ghs_minor,
       tone, size, rating, review_count, tags, image_path, created_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.BrandID,
		&i.CategoryID,
		&i.PriceGhsMinor,
		&i.WasPriceGhsMinor,
		&i.Tone,
		&i.Size,
		&i.Rating,
		&i.ReviewCount,
		&i.Tags,
		&i.ImagePath,
		&i.CreatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, slug, name, brand_id, category_id, price_ghs_minor, was_price_ghs_minor,
       tone, size, rating, review_count, tags, image_path, created_at
FROM products
WHERE slug = $1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.BrandID,
		&i.CategoryID,
		&i.PriceGhsMinor,
		&i.WasPriceGhsMinor,
		&i.Tone,
		&i.Size,
		&i.Rating,
		&i.ReviewCount,
		&i.Tags,
		&i.ImagePath,
		&i.CreatedAt,
	)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT id, slug, name
FROM brands
ORDER BY name ASC
`

func (q *Queries) ListBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.Query(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, slug, label, sort_order
FROM categories
ORDER BY sort_order ASC, label ASC
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Label,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByName = `-- name: ListProductsByName :many
SELECT p.id, p.slug, p.name, p.brand_id, p.category_id, p.price_ghs_minor, p.was_price_ghs_minor,
       p.tone, p.size, p.rating, p.review_count, p.tags, p.image_path, p.created_at
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
LEFT JOIN brands     b ON b.id = p.brand_id
WHERE ($3::text IS NULL OR c.slug = $3)
  AND ($4::text    IS NULL OR b.slug = $4)
  AND ($5::text           IS NULL OR p.tags && ARRAY[$5::text])
  AND ($6::text             IS NULL OR p.name ILIKE '%' || $6 || '%')
ORDER BY p.name ASC
LIMIT $1 OFFSET $2
`

type ListProductsByNameParams struct {
	Limit        int32
	Offset       int32
	CategorySlug *string
	BrandSlug    *string
	Tag          *string
	Q            *string
}

func (q *Queries) ListProductsByName(ctx context.Context, arg ListProductsByNameParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByName,
		arg.Limit,
		arg.Offset,
		arg.CategorySlug,
		arg.BrandSlug,
		arg.Tag,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BrandID,
			&i.CategoryID,
			&i.PriceGhsMinor,
			&i.WasPriceGhsMinor,
			&i.Tone,
			&i.Size,
			&i.Rating,
			&i.ReviewCount,
			&i.Tags,
			&i.ImagePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByNewest = `-- name: ListProductsByNewest :many
SELECT p.id, p.slug, p.name, p.brand_id, p.category_id, p.price_ghs_minor, p.was_price_ghs_minor,
       p.tone, p.size, p.rating, p.review_count, p.tags, p.image_path, p.created_at
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
LEFT JOIN brands     b ON b.id = p.brand_id
WHERE ($3::text IS NULL OR c.slug = $3)
  AND ($4::text    IS NULL OR b.slug = $4)
  AND ($5::text           IS NULL OR p.tags && ARRAY[$5::text])
  AND ($6::text             IS NULL OR p.name ILIKE '%' || $6 || '%')
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsByNewestParams struct {
	Limit        int32
	Offset       int32
	CategorySlug *string
	BrandSlug    *string
	Tag          *string
	Q            *string
}

func (q *Queries) ListProductsByNewest(ctx context.Context, arg ListProductsByNewestParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByNewest,
		arg.Limit,
		arg.Offset,
		arg.CategorySlug,
		arg.BrandSlug,
		arg.Tag,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BrandID,
			&i.CategoryID,
			&i.PriceGhsMinor,
			&i.WasPriceGhsMinor,
			&i.Tone,
			&i.Size,
			&i.Rating,
			&i.ReviewCount,
			&i.Tags,
			&i.ImagePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByPriceAsc = `-- name: ListProductsByPriceAsc :many
SELECT p.id, p.slug, p.name, p.brand_id, p.category_id, p.price_ghs_minor, p.was_price_ghs_minor,
       p.tone, p.size, p.rating, p.review_count, p.tags, p.image_path, p.created_at
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
LEFT JOIN brands     b ON b.id = p.brand_id
WHERE ($3::text IS NULL OR c.slug = $3)
  AND ($4::text    IS NULL OR b.slug = $4)
  AND ($5::text           IS NULL OR p.tags && ARRAY[$5::text])
  AND ($6::text             IS NULL OR p.name ILIKE '%' || $6 || '%')
ORDER BY p.price_ghs_minor ASC
LIMIT $1 OFFSET $2
`

type ListProductsByPriceAscParams struct {
	Limit        int32
	Offset       int32
	CategorySlug *string
	BrandSlug    *string
	Tag          *string
	Q            *string
}

func (q *Queries) ListProductsByPriceAsc(ctx context.Context, arg ListProductsByPriceAscParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByPriceAsc,
		arg.Limit,
		arg.Offset,
		arg.CategorySlug,
		arg.BrandSlug,
		arg.Tag,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BrandID,
			&i.CategoryID,
			&i.PriceGhsMinor,
			&i.WasPriceGhsMinor,
			&i.Tone,
			&i.Size,
			&i.Rating,
			&i.ReviewCount,
			&i.Tags,
			&i.ImagePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByPriceDesc = `-- name: ListProductsByPriceDesc :many
SELECT p.id, p.slug, p.name, p.brand_id, p.category_id, p.price_ghs_minor, p.was_price_ghs_minor,
       p.tone, p.size, p.rating, p.review_count, p.tags, p.image_path, p.created_at
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
LEFT JOIN brands     b ON b.id = p.brand_id
WHERE ($3::text IS NULL OR c.slug = $3)
  AND ($4::text    IS NULL OR b.slug = $4)
  AND ($5::text           IS NULL OR p.tags && ARRAY[$5::text])
  AND ($6::text             IS NULL OR p.name ILIKE '%' || $6 || '%')
ORDER BY p.price_ghs_minor DESC
LIMIT $1 OFFSET $2
`

type ListProductsByPriceDescParams struct {
	Limit        int32
	Offset       int32
	CategorySlug *string
	BrandSlug    *string
	Tag          *string
	Q            *string
}

func (q *Queries) ListProductsByPriceDesc(ctx context.Context, arg ListProductsByPriceDescParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByPriceDesc,
		arg.Limit,
		arg.Offset,
		arg.CategorySlug,
		arg.BrandSlug,
		arg.Tag,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BrandID,
			&i.CategoryID,
			&i.PriceGhsMinor,
			&i.WasPriceGhsMinor,
			&i.Tone,
			&i.Size,
			&i.Rating,
			&i.ReviewCount,
			&i.Tags,
			&i.ImagePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByRating = `-- name: ListProductsByRating :many
SELECT p.id, p.slug, p.name, p.brand_id, p.category_id, p.price_ghs_minor, p.was_price_ghs_minor,
       p.tone, p.size, p.rating, p.review_count, p.tags, p.image_path, p.created_at
FROM products p
LEFT JOIN categories c ON c.id = p.category_id
LEFT JOIN brands     b ON b.id = p.brand_id
WHERE ($3::text IS NULL OR c.slug = $3)
  AND ($4::text    IS NULL OR b.slug = $4)
  AND ($5::text           IS NULL OR p.tags && ARRAY[$5::text])
  AND ($6::text             IS NULL OR p.name ILIKE '%' || $6 || '%')
ORDER BY p.rating DESC NULLS LAST
LIMIT $1 OFFSET $2
`

type ListProductsByRatingParams struct {
	Limit        int32
	Offset       int32
	CategorySlug *string
	BrandSlug    *string
	Tag          *string
	Q            *string
}

func (q *Queries) ListProductsByRating(ctx context.Context, arg ListProductsByRatingParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByRating,
		arg.Limit,
		arg.Offset,
		arg.CategorySlug,
		arg.BrandSlug,
		arg.Tag,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.BrandID,
			&i.CategoryID,
			&i.PriceGhsMinor,
			&i.WasPriceGhsMinor,
			&i.Tone,
			&i.Size,
			&i.Rating,
			&i.ReviewCount,
			&i.Tags,
			&i.ImagePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
