// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlc

import (
	"context"
)

const countHealthMarkers = `-- name: CountHealthMarkers :one
SELECT count(*) FROM health_marker
`

func (q *Queries) CountHealthMarkers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countHealthMarkers)
	var count int64
	err := row.Scan(&count)
	return count, err
}
