// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Brand struct {
	ID   uuid.UUID
	Slug string
	Name string
}

type Category struct {
	ID        uuid.UUID
	Slug      string
	Label     string
	SortOrder int32
}

type HealthMarker struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type OauthAccount struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Provider          string
	ProviderAccountID string
	CreatedAt         pgtype.Timestamptz
}

type PasswordCredential struct {
	UserID       uuid.UUID
	PasswordHash string
	UpdatedAt    pgtype.Timestamptz
}

type Product struct {
	ID               uuid.UUID
	Slug             string
	Name             string
	BrandID          uuid.UUID
	CategoryID       uuid.UUID
	PriceGhsMinor    int64
	WasPriceGhsMinor *int64
	Tone             string
	Size             string
	Rating           pgtype.Numeric
	ReviewCount      int32
	Tags             []string
	ImagePath        string
	CreatedAt        pgtype.Timestamptz
}

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	ExpiresAt  pgtype.Timestamptz
	Ip         *netip.Addr
	UserAgent  string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

type User struct {
	ID            uuid.UUID
	Email         string
	Name          string
	Image         *string
	EmailVerified bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type UserRole struct {
	UserID uuid.UUID
	Role   string
}

type VerificationToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
