// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Brand struct {
	ID   uuid.UUID
	Slug string
	Name string
}

type Category struct {
	ID        uuid.UUID
	Slug      string
	Label     string
	SortOrder int32
}

type HealthMarker struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type Product struct {
	ID               uuid.UUID
	Slug             string
	Name             string
	BrandID          uuid.UUID
	CategoryID       uuid.UUID
	PriceGhsMinor    int64
	WasPriceGhsMinor *int64
	Tone             string
	Size             string
	Rating           pgtype.Numeric
	ReviewCount      int32
	Tags             []string
	ImagePath        string
	CreatedAt        pgtype.Timestamptz
}
