// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countOrdersByStatus = `-- name: CountOrdersByStatus :one
SELECT count(*) FROM orders WHERE status = $1
`

func (q *Queries) CountOrdersByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByUserID = `-- name: CountOrdersByUserID :one
SELECT count(*) FROM orders
WHERE user_id = $1
  AND ($2::text = '' OR status = $2)
`

type CountOrdersByUserIDParams struct {
	UserID uuid.UUID
	Status *string
}

func (q *Queries) CountOrdersByUserID(ctx context.Context, arg CountOrdersByUserIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByUserID, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, status, subtotal_ghs_minor, shipping_ghs_minor,
                    total_ghs_minor, paystack_reference, shipping_address)
VALUES ($1, 'pending', $2, $3, $4, $5, $6)
RETURNING id, user_id, status, subtotal_ghs_minor, shipping_ghs_minor,
          total_ghs_minor, paystack_reference, paystack_transaction_id,
          shipping_address, created_at, updated_at
`

type CreateOrderParams struct {
	UserID            uuid.UUID
	SubtotalGhsMinor  int64
	ShippingGhsMinor  int64
	TotalGhsMinor     int64
	PaystackReference string
	ShippingAddress   []byte
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.SubtotalGhsMinor,
		arg.ShippingGhsMinor,
		arg.TotalGhsMinor,
		arg.PaystackReference,
		arg.ShippingAddress,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalGhsMinor,
		&i.ShippingGhsMinor,
		&i.TotalGhsMinor,
		&i.PaystackReference,
		&i.PaystackTransactionID,
		&i.ShippingAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, qty, unit_price_ghs_minor,
                         product_name_snapshot, product_brand_snapshot,
                         product_image_snapshot)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, order_id, product_id, qty, unit_price_ghs_minor,
          product_name_snapshot, product_brand_snapshot,
          product_image_snapshot, created_at
`

type CreateOrderItemParams struct {
	OrderID              uuid.UUID
	ProductID            uuid.UUID
	Qty                  int32
	UnitPriceGhsMinor    int64
	ProductNameSnapshot  string
	ProductBrandSnapshot string
	ProductImageSnapshot string
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Qty,
		arg.UnitPriceGhsMinor,
		arg.ProductNameSnapshot,
		arg.ProductBrandSnapshot,
		arg.ProductImageSnapshot,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Qty,
		&i.UnitPriceGhsMinor,
		&i.ProductNameSnapshot,
		&i.ProductBrandSnapshot,
		&i.ProductImageSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, status, subtotal_ghs_minor, shipping_ghs_minor,
       total_ghs_minor, paystack_reference, paystack_transaction_id,
       shipping_address, created_at, updated_at
FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalGhsMinor,
		&i.ShippingGhsMinor,
		&i.TotalGhsMinor,
		&i.PaystackReference,
		&i.PaystackTransactionID,
		&i.ShippingAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByReference = `-- name: GetOrderByReference :one
SELECT id, user_id, status, subtotal_ghs_minor, shipping_ghs_minor,
       total_ghs_minor, paystack_reference, paystack_transaction_id,
       shipping_address, created_at, updated_at
FROM orders WHERE paystack_reference = $1
`

func (q *Queries) GetOrderByReference(ctx context.Context, paystackReference string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByReference, paystackReference)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalGhsMinor,
		&i.ShippingGhsMinor,
		&i.TotalGhsMinor,
		&i.PaystackReference,
		&i.PaystackTransactionID,
		&i.ShippingAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByReferenceForUpdate = `-- name: GetOrderByReferenceForUpdate :one
SELECT id, user_id, status, subtotal_ghs_minor, shipping_ghs_minor,
       total_ghs_minor, paystack_reference, paystack_transaction_id,
       shipping_address, created_at, updated_at
FROM orders WHERE paystack_reference = $1
FOR UPDATE
`

func (q *Queries) GetOrderByReferenceForUpdate(ctx context.Context, paystackReference string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByReferenceForUpdate, paystackReference)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalGhsMinor,
		&i.ShippingGhsMinor,
		&i.TotalGhsMinor,
		&i.PaystackReference,
		&i.PaystackTransactionID,
		&i.ShippingAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, qty, unit_price_ghs_minor,
       product_name_snapshot, product_brand_snapshot,
       product_image_snapshot, created_at
FROM order_items
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Qty,
			&i.UnitPriceGhsMinor,
			&i.ProductNameSnapshot,
			&i.ProductBrandSnapshot,
			&i.ProductImageSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT id, user_id, status, subtotal_ghs_minor, shipping_ghs_minor,
       total_ghs_minor, paystack_reference, paystack_transaction_id,
       shipping_address, created_at, updated_at
FROM orders
WHERE user_id = $1
  AND ($2::text = '' OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListOrdersByUserIDParams struct {
	UserID uuid.UUID
	Status *string
	Offset *int32
	Limit  *int32
}

func (q *Queries) ListOrdersByUserID(ctx context.Context, arg ListOrdersByUserIDParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID,
		arg.UserID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.SubtotalGhsMinor,
			&i.ShippingGhsMinor,
			&i.TotalGhsMinor,
			&i.PaystackReference,
			&i.PaystackTransactionID,
			&i.ShippingAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderPaid = `-- name: MarkOrderPaid :exec
UPDATE orders
SET status = 'paid',
    paystack_transaction_id = $2,
    updated_at = now()
WHERE id = $1 AND status = 'pending'
`

type MarkOrderPaidParams struct {
	ID                    uuid.UUID
	PaystackTransactionID *string
}

func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) error {
	_, err := q.db.Exec(ctx, markOrderPaid, arg.ID, arg.PaystackTransactionID)
	return err
}
